---
trigger:
    branches:
      include:
      - master
      - beta
      - preview
    paths:
      exclude:
      - CHANGELOG.md

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

jobs:
- job: build_pack_publish

  steps:
  - checkout: self
    clean: true
    persistCredentials: true

  - task: UseDotNet@2
    displayName: 'Use .NET 6 Core sdk'
    enabled: false
    inputs:
      packageType: sdk
      version: 6.0.x
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: DotNetCoreCLI@2
    name: build
    inputs:
      command: 'build'
      projects: 'src/*/*.csproj'

  - task: Bash@3
    name: release
    displayName: release+pack (SemRel)
    env:
      STAGING_PATH: $(Build.StagingDirectory)
      LOCAL_PATH: $(Build.Repository.LocalPath)
    inputs:
      targetType: 'inline'
      script: |
        time curl -L https://github.com/Elders/blob/releases/download/SemRel-01/node_modules.tar.gz | tar mx -I pigz
        time npx semantic-release --no-ci
        # few commands for debugging purposes
        ls -l $STAGING_PATH/*.nupkg
        echo dotnet msbuild `dotnet msbuild --version`
        echo dotnet nuget `dotnet nuget --version`
        echo dotnet `dotnet --version`

  - task: NuGetCommand@2
    name: publish
    inputs:
      command: 'push'
      packagesToPush: '$(Build.StagingDirectory)/*.nupkg'
      nuGetFeedType: 'external'
      publishFeedCredentials: 'CI-AzurePipelines'
